# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://TheMaxCoder.github.io/
baseurl: ""
title: Atiq Ur Rehman
author: Atiq Ur Rehman
description: Personal blog
avatar: profile.png
email: atiq.codes@gmail.com
github: TheMaxCoder # username
twitter: TheMaxCoderr
instagram: TheMaxCoder
linkedin: TheMaxCoder
stackoverflow: /users/5699956/max   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus
#disqus: username
#google_analytics: UA-69391421-1


# needed for travis-ci build
exclude: [vendor]
